services:
    MargretSchroeder\ContaoStammBundle\Library\MessageGenerator:
        public: true

    MargretSchroeder\ContaoStammBundle\Controller\FrontendModule\BaumErstellungController:
            