services:
     MargretSchroeder\ContaoStammBundle\Library\MessageGenerator:
        public: true

     MargretSchroeder\ContaoStammBundle\Library\StammbaumPerson: ~
       

     MargretSchroeder\ContaoStammBundle\Controller\FrontendModule\BaumErstellungController: ~
 